### ISSUE TITLE
Define start-point with subdirectory in git repository?

### ISSUE THREAD

**Issue by abingham** [cyber-dojo/commander#13]
Is it possible to specify a subdirectory within a git repository when creating a start point? It doesn't seem to be supported, but this would be helpful for me. I've got a workshop that includes a number of components, including a cyber-dojo start point. But since the start point isn't at the root of the repo I can't use `cyber-dojo start-point create --git` when setting things up.

This isn't a show-stopper. I can always just clone the repo and the install with the `--dir` flag. But it would be convenient if I could just install in one step.

**Comment by JonJagger** [comment]
You are right - at the moment that is not possible. Sorry.
