### ISSUE TITLE
nginx fails to start

### ISSUE THREAD

**Issue by davidcurrie** [cyber-dojo/commander#3]
nginx now fails to start with the following error in the logs:

2016/11/07 22:07:44 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:2
2016/11/07 22:07:44 [emerg] 1#1: mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)

If I undo the change made under https://github.com/cyber-dojo/commander/commit/8875645c8cc2ed8e12312fb30222abd975fc61a5 then it starts successfully i.e. the container needs to start as root and then drop down to 'nobody' (or else it needs to have permissions for that directory).

**Comment by JonJagger** [comment]
Thanks David. Will look at that today.
